"""Add icon field to worlds

Revision ID: 1959f8f623ea
Revises: add_engagement_tables
Create Date: 2026-01-27 14:53:53.527483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1959f8f623ea'
down_revision: Union[str, None] = 'add_engagement_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enum types explicitly
    achievement_type_enum = sa.Enum('quest', 'combat', 'social', 'collection', 'mastery', name='achievementtype')
    achievement_type_enum.drop(op.get_bind(), checkfirst=True)
    achievement_type_enum.create(op.get_bind(), checkfirst=True)

    item_rarity_enum = sa.Enum('common', 'uncommon', 'rare', 'epic', 'legendary', name='itemrarity')
    item_rarity_enum.create(op.get_bind(), checkfirst=True)

    submission_status_enum = sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='submissionstatus')
    submission_status_enum.create(op.get_bind(), checkfirst=True)

    # Drop defaults first to avoid type mismatch
    op.alter_column('achievements', 'rarity', server_default=None)
    op.alter_column('submissions', 'status', server_default=None)

    op.alter_column('achievements', 'achievement_type',
               existing_type=postgresql.ENUM('quest', 'combat', 'social', 'collection', 'mastery', name='achievement_type'),
               type_=achievement_type_enum,
               existing_nullable=False,
               postgresql_using='achievement_type::text::achievementtype')
    op.alter_column('achievements', 'rarity',
               existing_type=postgresql.ENUM('common', 'uncommon', 'rare', 'epic', 'legendary', name='item_rarity'),
               type_=item_rarity_enum,
               existing_nullable=True,
               # existing_server_default should be ignored since we dropped it above, but keeping it for reference or as None?
               # Actually, we dropped it, so existing_server_default is effectively None now at this point of execution,
               # but Alembic might use matching logic. Safe to keep or remove.
               # We set the new default here.
               server_default=sa.text("'COMMON'::itemrarity"),
               postgresql_using='upper(rarity::text)::itemrarity')
    op.create_index(op.f('ix_achievements_achievement_id'), 'achievements', ['achievement_id'], unique=False)
    op.drop_table_comment(
        'achievements',
        existing_comment='The Trophies - Unlockable achievements',
        schema=None
    )
    op.drop_index('idx_assignments_quest_id', table_name='assignments')
    op.create_index(op.f('ix_assignments_assignment_id'), 'assignments', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignments_quest_id'), 'assignments', ['quest_id'], unique=False)
    op.drop_table_comment(
        'assignments',
        existing_comment='The Bounties - Manual tasks requiring submission',
        schema=None
    )
    op.create_index(op.f('ix_friendships_id'), 'friendships', ['id'], unique=False)
    op.drop_index('idx_leaderboard_user_id', table_name='leaderboard_entries')
    op.drop_index('idx_leaderboard_world_id', table_name='leaderboard_entries')
    op.drop_index('idx_leaderboard_xp', table_name='leaderboard_entries')
    op.create_index(op.f('ix_leaderboard_entries_entry_id'), 'leaderboard_entries', ['entry_id'], unique=False)
    op.create_index(op.f('ix_leaderboard_entries_user_id'), 'leaderboard_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_leaderboard_entries_world_id'), 'leaderboard_entries', ['world_id'], unique=False)
    op.drop_table_comment(
        'leaderboard_entries',
        existing_comment='The Hall of Fame - Player rankings and scores',
        schema=None
    )
    op.drop_index('idx_monsters_quest_id', table_name='monsters')
    op.create_index(op.f('ix_monsters_monster_id'), 'monsters', ['monster_id'], unique=False)
    op.create_index(op.f('ix_monsters_quest_id'), 'monsters', ['quest_id'], unique=False)
    op.drop_table_comment(
        'monsters',
        existing_comment='The Quizzes - Challenges to defeat with questions',
        schema=None
    )
    op.drop_index('idx_quests_order', table_name='quests')
    op.drop_index('idx_quests_zone_id', table_name='quests')
    op.create_index(op.f('ix_quests_quest_id'), 'quests', ['quest_id'], unique=False)
    op.create_index(op.f('ix_quests_zone_id'), 'quests', ['zone_id'], unique=False)
    op.drop_table_comment(
        'quests',
        existing_comment='The Lessons - Individual learning tasks',
        schema=None
    )
    op.drop_column('quests', 'description')
    op.drop_column('quests', 'quest_type')
    op.alter_column('quiz_questions', 'monster_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quiz_questions', 'wrong_answers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('quiz_questions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_quiz_questions_monster_id'), 'quiz_questions', ['monster_id'], unique=False)
    op.create_index(op.f('ix_quiz_questions_question_id'), 'quiz_questions', ['question_id'], unique=False)
    op.alter_column('submissions', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='submission_status'),
               type_=submission_status_enum,
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::submission_status"),
               server_default=sa.text("'PENDING'::submissionstatus"),
               postgresql_using='upper(status::text)::submissionstatus')
    op.drop_index('idx_submissions_assignment_id', table_name='submissions')
    op.drop_index('idx_submissions_status', table_name='submissions')
    op.drop_index('idx_submissions_user_id', table_name='submissions')
    op.create_index(op.f('ix_submissions_assignment_id'), 'submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_submissions_submission_id'), 'submissions', ['submission_id'], unique=False)
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    op.drop_table_comment(
        'submissions',
        existing_comment='The Contract Fulfillment - Student submissions for grading',
        schema=None
    )
    op.drop_constraint('teachers_email_key', 'teachers', type_='unique')
    op.drop_constraint('teachers_username_key', 'teachers', type_='unique')
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=True)
    op.create_index(op.f('ix_teachers_teacher_id'), 'teachers', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_teachers_username'), 'teachers', ['username'], unique=True)
    op.drop_table_comment(
        'teachers',
        existing_comment='The Guild Masters - Instructors who create and manage Worlds',
        schema=None
    )
    op.drop_index('idx_user_achievements_user_id', table_name='user_achievements')
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_achievement_id'), 'user_achievements', ['user_achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.drop_table_comment(
        'user_achievements',
        existing_comment='The Trophy Case - Achievements earned by players',
        schema=None
    )
    op.create_index(op.f('ix_user_activities_id'), 'user_activities', ['id'], unique=False)
    op.create_index(op.f('ix_user_daily_quests_id'), 'user_daily_quests', ['id'], unique=False)
    op.drop_index('idx_user_progress_quest_id', table_name='user_progress')
    op.drop_index('idx_user_progress_user_id', table_name='user_progress')
    op.create_index(op.f('ix_user_progress_progress_id'), 'user_progress', ['progress_id'], unique=False)
    op.create_index(op.f('ix_user_progress_quest_id'), 'user_progress', ['quest_id'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.drop_table_comment(
        'user_progress',
        existing_comment='The Save File - Tracks player progress through quests',
        schema=None
    )
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_table_comment(
        'users',
        existing_comment='The Heroes - Player accounts with RPG stats',
        schema=None
    )
    op.create_index(op.f('ix_weekly_goals_id'), 'weekly_goals', ['id'], unique=False)
    op.add_column('worlds', sa.Column('icon', sa.String(length=10), nullable=True))
    op.drop_index('idx_worlds_teacher_id', table_name='worlds')
    op.create_index(op.f('ix_worlds_teacher_id'), 'worlds', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_worlds_world_id'), 'worlds', ['world_id'], unique=False)
    op.drop_table_comment(
        'worlds',
        existing_comment='The Courses - Learning worlds to explore',
        schema=None
    )
    op.drop_index('idx_zones_order', table_name='zones')
    op.drop_index('idx_zones_world_id', table_name='zones')
    op.create_index(op.f('ix_zones_world_id'), 'zones', ['world_id'], unique=False)
    op.create_index(op.f('ix_zones_zone_id'), 'zones', ['zone_id'], unique=False)
    op.drop_table_comment(
        'zones',
        existing_comment='The Modules - Areas within each world',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'zones',
        'The Modules - Areas within each world',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_zones_zone_id'), table_name='zones')
    op.drop_index(op.f('ix_zones_world_id'), table_name='zones')
    op.create_index('idx_zones_world_id', 'zones', ['world_id'], unique=False)
    op.create_index('idx_zones_order', 'zones', ['world_id', 'order_index'], unique=False)
    op.create_table_comment(
        'worlds',
        'The Courses - Learning worlds to explore',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_worlds_world_id'), table_name='worlds')
    op.drop_index(op.f('ix_worlds_teacher_id'), table_name='worlds')
    op.create_index('idx_worlds_teacher_id', 'worlds', ['teacher_id'], unique=False)
    op.drop_column('worlds', 'icon')
    op.drop_index(op.f('ix_weekly_goals_id'), table_name='weekly_goals')
    op.create_table_comment(
        'users',
        'The Heroes - Player accounts with RPG stats',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_table_comment(
        'user_progress',
        'The Save File - Tracks player progress through quests',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_quest_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_progress_id'), table_name='user_progress')
    op.create_index('idx_user_progress_user_id', 'user_progress', ['user_id'], unique=False)
    op.create_index('idx_user_progress_quest_id', 'user_progress', ['quest_id'], unique=False)
    op.drop_index(op.f('ix_user_daily_quests_id'), table_name='user_daily_quests')
    op.drop_index(op.f('ix_user_activities_id'), table_name='user_activities')
    op.create_table_comment(
        'user_achievements',
        'The Trophy Case - Achievements earned by players',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_user_achievement_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.create_index('idx_user_achievements_user_id', 'user_achievements', ['user_id'], unique=False)
    op.create_table_comment(
        'teachers',
        'The Guild Masters - Instructors who create and manage Worlds',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_teachers_username'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_teacher_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.create_unique_constraint('teachers_username_key', 'teachers', ['username'])
    op.create_unique_constraint('teachers_email_key', 'teachers', ['email'])
    op.create_table_comment(
        'submissions',
        'The Contract Fulfillment - Student submissions for grading',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_submission_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_assignment_id'), table_name='submissions')
    op.create_index('idx_submissions_user_id', 'submissions', ['user_id'], unique=False)
    op.create_index('idx_submissions_status', 'submissions', ['status'], unique=False)
    op.create_index('idx_submissions_assignment_id', 'submissions', ['assignment_id'], unique=False)
    op.alter_column('submissions', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='submissionstatus'),
               type_=postgresql.ENUM('pending', 'approved', 'rejected', name='submission_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::submission_status"))
    op.drop_index(op.f('ix_quiz_questions_question_id'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_monster_id'), table_name='quiz_questions')
    op.alter_column('quiz_questions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('quiz_questions', 'wrong_answers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('quiz_questions', 'monster_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('quests', sa.Column('quest_type', sa.VARCHAR(length=50), server_default=sa.text("'lesson'::character varying"), autoincrement=False, nullable=True))
    op.add_column('quests', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table_comment(
        'quests',
        'The Lessons - Individual learning tasks',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_quests_zone_id'), table_name='quests')
    op.drop_index(op.f('ix_quests_quest_id'), table_name='quests')
    op.create_index('idx_quests_zone_id', 'quests', ['zone_id'], unique=False)
    op.create_index('idx_quests_order', 'quests', ['zone_id', 'order_index'], unique=False)
    op.create_table_comment(
        'monsters',
        'The Quizzes - Challenges to defeat with questions',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_monsters_quest_id'), table_name='monsters')
    op.drop_index(op.f('ix_monsters_monster_id'), table_name='monsters')
    op.create_index('idx_monsters_quest_id', 'monsters', ['quest_id'], unique=False)
    op.create_table_comment(
        'leaderboard_entries',
        'The Hall of Fame - Player rankings and scores',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_leaderboard_entries_world_id'), table_name='leaderboard_entries')
    op.drop_index(op.f('ix_leaderboard_entries_user_id'), table_name='leaderboard_entries')
    op.drop_index(op.f('ix_leaderboard_entries_entry_id'), table_name='leaderboard_entries')
    op.create_index('idx_leaderboard_xp', 'leaderboard_entries', [sa.text('total_xp DESC')], unique=False)
    op.create_index('idx_leaderboard_world_id', 'leaderboard_entries', ['world_id'], unique=False)
    op.create_index('idx_leaderboard_user_id', 'leaderboard_entries', ['user_id'], unique=False)
    op.drop_index(op.f('ix_friendships_id'), table_name='friendships')
    op.create_table_comment(
        'assignments',
        'The Bounties - Manual tasks requiring submission',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_assignments_quest_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assignment_id'), table_name='assignments')
    op.create_index('idx_assignments_quest_id', 'assignments', ['quest_id'], unique=False)
    op.create_table_comment(
        'achievements',
        'The Trophies - Unlockable achievements',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_achievements_achievement_id'), table_name='achievements')
    op.alter_column('achievements', 'rarity',
               existing_type=sa.Enum('common', 'uncommon', 'rare', 'epic', 'legendary', name='itemrarity'),
               type_=postgresql.ENUM('common', 'uncommon', 'rare', 'epic', 'legendary', name='item_rarity'),
               existing_nullable=True,
               existing_server_default=sa.text("'common'::item_rarity"))
    op.alter_column('achievements', 'achievement_type',
               existing_type=sa.Enum('quest', 'combat', 'social', 'collection', 'mastery', name='achievementtype'),
               type_=postgresql.ENUM('quest', 'combat', 'social', 'collection', 'mastery', name='achievement_type'),
               existing_nullable=False)
    # ### end Alembic commands ###
