"""create_ai_grading_log_table

Revision ID: 2961feb1d0c0
Revises: f1ebca8f9e72
Create Date: 2026-01-28 14:06:04.140260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2961feb1d0c0'
down_revision: Union[str, None] = 'f1ebca8f9e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_grading_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('score_awarded', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('status_verdict', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_grading_logs_id'), 'ai_grading_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_grading_logs_submission_id'), 'ai_grading_logs', ['submission_id'], unique=False)
    op.create_index(op.f('ix_ai_grading_logs_user_email'), 'ai_grading_logs', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_grading_logs_user_email'), table_name='ai_grading_logs')
    op.drop_index(op.f('ix_ai_grading_logs_submission_id'), table_name='ai_grading_logs')
    op.drop_index(op.f('ix_ai_grading_logs_id'), table_name='ai_grading_logs')
    op.drop_table('ai_grading_logs')
    # ### end Alembic commands ###
