"""verify_required_class_and_schema

Revision ID: 2d2e2ddc7dfa
Revises: 2961feb1d0c0
Create Date: 2026-02-01 13:24:49.508928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d2e2ddc7dfa'
down_revision: Union[str, None] = '2961feb1d0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assignments_assigned_to_user_id_fkey', 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'assigned_to_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('assigned_to_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('assignments_assigned_to_user_id_fkey', 'assignments', 'users', ['assigned_to_user_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###
